version: 2

sources:

  - name: raw
    schema: dbt_dataset

    tables:
      - name: product
        description: greenweez raw data
        identifier: raw_gz_product
      - name: sales
        description: information regarding our sales
        identifier: raw_gz_sales
        tests: 
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: ship
        description: information regarding our shipping costs
        identifier: raw_gz_ship

      - name: adwords
        description: information regarding adwords
        identifier: raw_gz_adwords

      - name: facebook
        description: information regarding facebook
        identifier: raw_gz_facebook

      - name: bing
        description: information regarding bing
        identifier: raw_gz_bing

      - name: criteo
        description: information regarding criteo
        identifier: raw_gz_criteo
models:
  - name: int_campaigns
    description: test for primary key
    tests:
      - unique:
           column_name: "(campaign_key || '-' || date_date)"
      - not_null:
            column_name:
              - paid_source
              - campaign_name
  
